// Code generated by counterfeiter. DO NOT EDIT.
package v2fakes

import (
	"sync"

	"code.cloudfoundry.org/cli/actor/v2action"
	"code.cloudfoundry.org/cli/command/v2"
)

type FakeCreateSpaceActor struct {
	CreateSpaceStub        func(spaceName, orgName, quotaName string) (v2action.Space, v2action.Warnings, error)
	createSpaceMutex       sync.RWMutex
	createSpaceArgsForCall []struct {
		spaceName string
		orgName   string
		quotaName string
	}
	createSpaceReturns struct {
		result1 v2action.Space
		result2 v2action.Warnings
		result3 error
	}
	createSpaceReturnsOnCall map[int]struct {
		result1 v2action.Space
		result2 v2action.Warnings
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCreateSpaceActor) CreateSpace(spaceName string, orgName string, quotaName string) (v2action.Space, v2action.Warnings, error) {
	fake.createSpaceMutex.Lock()
	ret, specificReturn := fake.createSpaceReturnsOnCall[len(fake.createSpaceArgsForCall)]
	fake.createSpaceArgsForCall = append(fake.createSpaceArgsForCall, struct {
		spaceName string
		orgName   string
		quotaName string
	}{spaceName, orgName, quotaName})
	fake.recordInvocation("CreateSpace", []interface{}{spaceName, orgName, quotaName})
	fake.createSpaceMutex.Unlock()
	if fake.CreateSpaceStub != nil {
		return fake.CreateSpaceStub(spaceName, orgName, quotaName)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.createSpaceReturns.result1, fake.createSpaceReturns.result2, fake.createSpaceReturns.result3
}

func (fake *FakeCreateSpaceActor) CreateSpaceCallCount() int {
	fake.createSpaceMutex.RLock()
	defer fake.createSpaceMutex.RUnlock()
	return len(fake.createSpaceArgsForCall)
}

func (fake *FakeCreateSpaceActor) CreateSpaceArgsForCall(i int) (string, string, string) {
	fake.createSpaceMutex.RLock()
	defer fake.createSpaceMutex.RUnlock()
	return fake.createSpaceArgsForCall[i].spaceName, fake.createSpaceArgsForCall[i].orgName, fake.createSpaceArgsForCall[i].quotaName
}

func (fake *FakeCreateSpaceActor) CreateSpaceReturns(result1 v2action.Space, result2 v2action.Warnings, result3 error) {
	fake.CreateSpaceStub = nil
	fake.createSpaceReturns = struct {
		result1 v2action.Space
		result2 v2action.Warnings
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCreateSpaceActor) CreateSpaceReturnsOnCall(i int, result1 v2action.Space, result2 v2action.Warnings, result3 error) {
	fake.CreateSpaceStub = nil
	if fake.createSpaceReturnsOnCall == nil {
		fake.createSpaceReturnsOnCall = make(map[int]struct {
			result1 v2action.Space
			result2 v2action.Warnings
			result3 error
		})
	}
	fake.createSpaceReturnsOnCall[i] = struct {
		result1 v2action.Space
		result2 v2action.Warnings
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCreateSpaceActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createSpaceMutex.RLock()
	defer fake.createSpaceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCreateSpaceActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v2.CreateSpaceActor = new(FakeCreateSpaceActor)
